### ISSUE TITLE
Deposit

### ISSUE THREAD

**Issue by DidrikxD** [ImpulseFPS/simple-banking#15]
If i have 10,000 and try to deposit 10,000 its says i dont have that much money, so i need to put in 9999. like i always have 1 dollar in cash that i cant put in

**Comment by ImpulseFPS** [comment]
can you contact me on discord since i don't have the server installed on this pc and I'm not planning to install it in the near future so you can test the change?

**Comment by DidrikxD** [comment]
Yes have you posted your disc somewhere? :)

**Comment by ImpulseFPS** [comment]
ImpulseFPS#3613
