### ISSUE TITLE
[HELP] - Can someone help me add the targets to the qb-target

### ISSUE THREAD

**Issue by NocityRP** [ImpulseFPS/simple-banking#16]
I have added the peds to ms-peds, but need help setting up the 3rd eye. It would be greatly appreciated

**Comment by ImpulseFPS** [comment]
I mean target is simple to set up drag and drop edit config.lua to add targets and you are done lol

**Comment by ImpulseFPS** [comment]
["atms"] = {
        models = {
            `prop_atm_01`,
            `prop_atm_02`,
            `prop_atm_03`,
            `prop_fleeca_atm`
        },
        options = {
            {
                type = "client",
                event = "qb-banking:client:atm:openUI",
                icon = "fab fa-cc-visa",
                label = "Use ATM",
            },
        },
        distance = 1.0
    },
	["big_bank"] = {
        models = {
            `ig_bankman`
        },
        options = {
            {
                type = "client",
                event = "qb-banking:client:bank:openUI",
                icon = "fas fa-circle",
                label = "Bank",
            },
            {
                type = "server",
                event = "qb-banking:server:Paycheck:pickup",
                icon = "fas fa-circle",
                label = "PayCheck",
            },
        },
        distance = 1.5
    },
