### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by cummins24v** [ImpulseFPS/simple-banking#18]
i got the bank ped in place when i go to use qb-target it dont pop up

**Comment by ImpulseFPS** [comment]
any errors?

**Comment by cummins24v** [comment]
no errors

**Comment by ImpulseFPS** [comment]
bruh you got to give me something to work with like saying "it does not work" doesn't really help in fixing the issue..

**Comment by NotPhelps** [comment]
["bank"] = {
        models = {
      `ig_bankman`,

        },
        options = {
            {
                event = "qb-banking:client:bank:openUI",
                icon = "fas fa-money-check-alt",
                label = "Talk To Banker", 
            },
        },
        distance = 10.0
    },

["ATM"] = {
        models = {
            `prop_atm_01`,
            `prop_atm_02`,
            `prop_atm_03`,
            `prop_fleeca_atm`,
        },
        options = {
            {
                type = "client",
                event = "qb-banking:client:atm:openUI",
                parameters = {},
                icon = "fab fa-cc-visa",
                label = "Use ATM",
            },
        },
        distance = 3.0
    },
add these to the qb target
