### ISSUE TITLE
Not working anymore after 1 time use, after restart the resource it works

### ISSUE THREAD

**Issue by meistroburger** [ImpulseFPS/simple-banking#20]
If I restart the resource the NUI is working, but If I use the bank again, it only show a mouse and no UI

Video: https://streamable.com/6cwz6j

**Comment by ImpulseFPS** [comment]
IDK no one i know had that issue..
if you did change anything revert it back.

**Comment by meistroburger** [comment]
Did revert it, rebuild it... But its not working

**Comment by ImpulseFPS** [comment]
Just download new fils feom releases and try it

**Comment by meistroburger** [comment]
I've tested it out. As I don't have a business attached, it works. As soon If I've a business attached, it works ONCE

**Comment by ImpulseFPS** [comment]
errors in server or F8 console?

**Comment by meistroburger** [comment]
Nope nothing

**Comment by WrecksBG** [comment]
same with me

**Comment by ImpulseFPS** [comment]
if you are on the latest oxmysql it won't work so either try adapting the exports for sql to the new version or revert back to the old oxmysql
