### ISSUE TITLE
Bank Card Intergration?

### ISSUE THREAD

**Issue by hoodz123** [ImpulseFPS/simple-banking#25]
Be Nice If We Could Get A Bank ??????????..............................

**Comment by ImpulseFPS** [comment]
> Be Nice If We Could Get A Bank ??????????..............................

what do you mean? lol

**Comment by hoodz123** [comment]
Sorry Bro I Mean When I Go To The Bank It Says Need Bank Card But No Option

**Comment by ImpulseFPS** [comment]
wtf are you even on about right now? you dont need anything except qb-target to run the banking

**Comment by hoodz123** [comment]
are you english ? so actually ready what im putting i have my atms set up but when you go to use it says you need a bank card so can you integrate bank card and pin numbers? simple question really

**Comment by ImpulseFPS** [comment]
AGAIN https://streamable.com/0z6w6x what are you on about? what notification says you need a card i  want you to go in client and server-side and look for that specific notification.
