### ISSUE TITLE
Scaling Issues past 1080p

### ISSUE THREAD

**Issue by SoStressful** [ImpulseFPS/simple-banking#27]
The banking UI doesn't scale properly past 1080p.

1080p
https://i.imgur.com/NXGOQ6T.jpeg

1440p 
https://i.imgur.com/XBWQp1e.jpeg

3840x2160p(4k)
https://i.imgur.com/3PUkFFR.jpeg

**Comment by ImpulseFPS** [comment]
That's because it does not support 1440 and 4k lol
