### ISSUE TITLE
want to add transaction

### ISSUE THREAD

**Issue by SmaDababaXor** [ImpulseFPS/simple-banking#30]
i want to add transactions for example when buying a vehicle and removes the money from bank it will say 

Message
Bought vehicle T20 for 10,000$

is there a trigger for that?

**Comment by ImpulseFPS** [comment]
exports['simple-banking']:AddTransaction(source, sAccount, iAmount, sType, sReceiver, sMessage)

**Comment by SmaDababaXor** [comment]
thanks
