### ISSUE TITLE
How to add other business account and give people access

### ISSUE THREAD

**Issue by Luma-exe** [ImpulseFPS/simple-banking#31]
I am confused on how to do this?

**Comment by ImpulseFPS** [comment]
read the readME

**Comment by Luma-exe** [comment]
https://i.imgur.com/hpZq3kH.png

I have done this but with the rank grade 7 for police which is "Inspector" or any rank that isn't called "boss" I cannot see the society account

**Comment by ImpulseFPS** [comment]
everything HAS to be without capital leathers.
