### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by DankHarry** [ImpulseFPS/simple-banking#33]
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:747: SCRIPT ERROR: @trd-banking/lua/server/sv_banking.lua:56: trd-banking was unable to execute a query!
[      script:qb-core] Unknown column 'citizenid' in 'where clause'
[      script:qb-core] SELECT * FROM transaction_history WHERE citizenid =  ? AND DATE(date) > (NOW() - INTERVAL 5 DAY) ["PUY52528"]
[      script:qb-core] > ref (@trd-banking/lua/server/sv_banking.lua:56)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:21765)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:21735)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:207)
[      script:qb-core] > handler (@qb-core/server/events.lua:110)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:21765)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] > async rawQuery (@oxmysql/dist/build.js:21735)

**Comment by ImpulseFPS** [comment]
You are using trd-banking witch is not simple-banking so please go to the cfx forum and ask there for help with this issue.
